name: armv8-db

on:
  repository_dispatch:
    types: [armv8db,ssharmv8db]
  workflow_dispatch:
    inputs:
      ssh:
        description: 'armv8db'
        required: false
        default: 'false'
  #schedule:
    #- cron: 00 16 * * *

env:
  TZ: Asia/Shanghai
  FILE_NAME: armv8

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:   
    - name: WeChat notification #pushbotæ¨é€
      run: curl -H "Content-Type:application/json" -X POST -d '{"token":"${{ secrets.pushbot }}","title":"Actions-armv8æ‰“åŒ…","content":"${{ env.FILE_NAME }}å¼€å§‹æ‰“åŒ…","template":"json"}' http://www.pushplus.plus/send

    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        echo "DATE=$(date "+%Yå¹´%mæœˆ%dæ—¥%Hæ—¶%Måˆ†")" >> $GITHUB_ENV
        echo "DATE1=$(date "+%Y.%m.%d")" >> $GITHUB_ENV

    - name: æ‰“åŒ…é•œåƒ
      uses: unifreq/openwrt_packit@master
      env:
        OPENWRT_ARMVIRT: https://github.com/binge8/op/releases/download/å…¬å‘Š/openwrt-armvirt-64-default-rootfs.tar.gz
        PACKAGE_SOC: s905x3
        KERNEL_VERSION_NAME: 5.15.15

    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: ${{ env.PACKAGED_STATUS }} == 'success' && env.UPLOAD_BIN_DIR == 'true' && !cancelled()
      with:
        name: armv8
        path: ${{ env.PACKAGED_OUTPUTPATH }}

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: env.UPLOAD_FIRMWARE == 'true' && ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
      with:
        name: armv8
        path: ${{ env.PACKAGED_OUTPUTPATH }}

    - name: Create release
      uses: ncipollo/release-action@v1
      if: env.UPLOAD_RELEASE == 'true' && ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
      with:
        name: ${{ env.DATE }} ğŸš€ armv8 | è‡ªåŠ¨ç¼–è¯‘
        allowUpdates: true
        tag: armv8
        commit: master
        token: ${{ secrets.RELEASES_TOKEN }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*

    - name: WeChat notification #pushbotæ¨é€
      if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
      run: curl -H "Content-Type:application/json" -X POST -d '{"token":"${{ secrets.pushbot }}","title":"Actions-armv8æ‰“åŒ…","content":"${{ env.FILE_NAME }}å‘å¸ƒæˆåŠŸ-æ‰“åŒ…ç»“æŸ${{ env.time }}","template":"json"}' http://www.pushplus.plus/send
