name: Delete workflow runs

on:
  repository_dispatch:
    types: [dl]
  schedule:
    - cron: 0 0 */5 * *

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    #删除旧的编译记录
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 2

    - name: WeChat notification #pushbot推送
      run: curl -H "Content-Type:application/json" -X POST -d '{"token":"${{ secrets.pushbot }}","title":"Actions运行记录清理>op","content":"清理成功","template":"json"}' http://www.pushplus.plus/send
